name: solar-station
channels:
  - defaults
dependencies:
  - aiohttp=3.8.5
  - aiosignal=1.2.0
  - async-timeout=4.0.2
  - attrs=23.1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2023.08.22
  - certifi=2023.7.22
  - cffi=1.16.0
  - charset-normalizer=2.0.4
  - cryptography=41.0.3
  - elasticsearch=7.13.3
  - frozenlist=1.4.0
  - idna=3.4
  - libcxx=14.0.6
  - libffi=3.4.4
  - multidict=6.0.2
  - ncurses=6.4
  - openssl=3.0.12
  - pip=23.3
  - pycparser=2.21
  - pyopenssl=23.2.0
  - pysocks=1.7.1
  - python=3.11.5
  - readline=8.2
  - requests=2.31.0
  - setuptools=68.0.0
  - sqlite=3.41.2
  - tk=8.6.12
  - tzdata=2023c
  - urllib3=1.26.18
  - wheel=0.41.2
  - xz=5.4.2
  - yarl=1.8.1
  - zlib=1.2.13
  - pip:
      - paho-mqtt==1.6.1
